import type { TrackingSnapshot } from "../types/tracking";

export const demoSnapshot: TrackingSnapshot = {
  teamName: "FutureHack",
  projects: [
    {
      id: "proj_alpha",
      name: "Campus Contribution Tracker",
      description: "Core web app and analytics",
      adminId: "admin_demo",
      memberIds: ["user1", "user2"],
      createdAt: "2026-02-25T08:00:00Z",
    },
    {
      id: "proj_beta",
      name: "Contribution Tracker",
      description: "Cross-platform contribution tracking",
      adminId: "admin_demo",
      memberIds: ["user1", "user2", "user3", "user4"],
      createdAt: "2026-02-26T08:00:00Z",
    },
  ],
  members: [
    {
      id: "user1",
      name: "User1",
      email: "user1@futurehack.dev",
      isTeamLead: true,
      isAvailable: true,
      githubUsername: "user1-dev",
      googleEmail: "user1@futurehack.dev",
      figmaHandle: "user1.design",
    },
    {
      id: "user2",
      name: "User2",
      email: "user2@futurehack.dev",
      isAvailable: true,
      githubUsername: "user2-dev",
      googleEmail: "user2@futurehack.dev",
      figmaHandle: "user2.design",
    },
    {
      id: "user3",
      name: "User3",
      email: "user3@futurehack.dev",
      isAvailable: true,
    },
    {
      id: "user4",
      name: "User4",
      email: "user4@futurehack.dev",
      isAvailable: true,
    },
  ],
  events: [
    {
      id: "e1",
      memberId: "user1",
      projectId: "proj_alpha",
      platform: "canva",
      type: "task_created",
      createdAt: "2026-02-27T08:35:00Z",
    },
    {
      id: "e2",
      memberId: "user1",
      projectId: "proj_alpha",
      platform: "github",
      type: "pr_merged",
      createdAt: "2026-02-27T09:15:00Z",
    },
    {
      id: "e3",
      memberId: "user2",
      projectId: "proj_beta",
      platform: "canva",
      type: "task_completed",
      createdAt: "2026-02-27T09:55:00Z",
    },
    {
      id: "e4",
      memberId: "user2",
      projectId: "proj_beta",
      platform: "canva",
      type: "deadline_bonus",
      createdAt: "2026-02-27T10:05:00Z",
    },
    {
      id: "e5",
      memberId: "user1",
      projectId: "proj_alpha",
      platform: "google_docs",
      type: "comment",
      createdAt: "2026-02-27T10:20:00Z",
    },
    {
      id: "e6",
      memberId: "user2",
      projectId: "proj_beta",
      platform: "canva",
      type: "peer_validation",
      createdAt: "2026-02-27T11:00:00Z",
    },
  ],
  tasks: [
    {
      id: "t1",
      projectId: "proj_alpha",
      title: "API integration audit",
      assigneeId: "user1",
      dueDate: "2026-03-03",
      estimateHours: 6,
      status: "in_progress",
    },
    {
      id: "t2",
      projectId: "proj_beta",
      title: "Dashboard UX cleanup",
      assigneeId: "user2",
      dueDate: "2026-03-02",
      estimateHours: 4,
      status: "todo",
    },
  ],
  exchangeRequests: [],
  projectRequests: [],
  integrations: [
    { provider: "github", status: "connected", connectedAt: "2026-02-21" },
    { provider: "google_docs", status: "connected", connectedAt: "2026-02-22" },
    { provider: "figma", status: "pending" },
    { provider: "canva", status: "connected", connectedAt: "2026-02-22" },
  ],
  timeLimits: [
    { label: "Sprint 8 Deadline", dueDate: "2026-03-04T18:00:00" },
    { label: "Client Demo", dueDate: "2026-03-08T11:00:00" },
    { label: "Final Report Submission", dueDate: "2026-03-11T20:00:00" },
  ],
};
